### ISSUE TITLE
Increase upload speed?

### ISSUE THREAD

**Issue by kaiser62** [hlf20010508/telegram-onedrive#25] opened 2024-06-10 23:40 UTC
theoretically is there a way to increase upload speed?
doesnt matter if local storage temporarily is used to make uploads faster.

**Comment by kaiser62** [comment] 2024-06-10 23:42
Also I'd like to share that docker deployment can be done on Google Colab with udocker. 

https://github.com/drengskapur/docker-in-colab

Used this notebook and modified it to use my volume that was generated by me locally on my system.

**Comment by kaiser62** [comment] 2024-06-10 23:49
Also [this](https://devblogs.microsoft.com/microsoft365dev/important-update-on-onedrive-url-upload-feature/).

Remote upload has been discontinued by onedrive.

**Comment by hlf20010508** [comment] 2024-06-11 01:32
> Also [this](https://devblogs.microsoft.com/microsoft365dev/important-update-on-onedrive-url-upload-feature/).
> 
> 
> 
> Remote upload has been discontinued by onedrive.

Thanks for sharing this important information.

And yes, the upload speed can be faster if the the onedrive remote download api fails. The bot would fallback to use its local uploader. And still, no need for local storage.

So I'll just remove using onedrive remote download api and use local uploader directly.

**Comment by kaiser62** [comment] 2024-06-11 01:41
Thanks for your quick reply. 
This is an awesome project. 

I also had an feature request.  Is it possible to give /links command an links.txt file from which it can read telegram/any direct links? It'd be helpful for downloading a large amount of files from a channel. 

Looking forward to updates and newer features.

**Comment by hlf20010508** [comment] 2024-06-11 02:16
It’s a good feature, but currently there’s some difficulty.

Because the whole program was written under the option `sequential_updates=false`, which means the bot can only handle one command at once. Conversation is not supported.

But `/links` is a command, uploading a file is also a command.

I know changing to `sequential_updates=true` is possible, but it need a lot of work.

Currently one solution is to allow `/links` to pass more links, like `/links multi link1 link2 link3`. So that `/links $link $range` is used for sequential links, `/links multi` will be used for scattered links. Also `/url multi`.

Another solution is to allow a file with specific extension to be used for `/links` and `/url` without being uploaded to onedrive, like `.t2o`. It seems no file is using `.t2o` as it’s extension. The content can be like
```
[links]
link1
link2, $range
link3

[urls]
url1
url2
```

And I think solution 2 is better, more convinient, and can be generated by scraper.

What do you think?

**Comment by kaiser62** [comment] 2024-06-11 02:38
I agree with you. Solution 2 seems far better than having to stack links one after another. 

Also I couldn't find a command to stop a task once its started, is there a command for that?

**Comment by hlf20010508** [comment] 2024-06-11 02:40
> I agree with you. Solution 2 seems far better than having to stack links one after another.
> 
> Also I couldn't find a command to stop a task once its started, is there a command for that?

No. Same reason by `sequential_updates=false`.

**Comment by hlf20010508** [comment] 2024-06-11 04:27
I've updated.

Please try dev image `:dev` to have a test.

**Comment by hlf20010508** [comment] 2024-06-12 02:15
Is there any problem?
If not, I'll publish new version.

**Comment by kaiser62** [comment] 2024-06-12 13:46
Sorry For the late reply.
No, there were no problems. Although I didn't see noticeable upload speed changes. 
The bot works fine.

As for link.txt, I have made myself a workaround. 
Basically i got myself a python script running, that takes in a link.txt file and send each link as messages with "/link " prefix. Working fine, tried with 2000 links.

**Comment by hlf20010508** [comment] 2024-06-12 14:16
Yes the speed is lower than 10MB/s for me.
It's somehow telegram's problem. Maybe it can be improved in the future.
The speed should be more stable compared to remote download.

And really glad to see your work!
It shows the potential that `.t2o` can be a script for this bot, to create sequential jobs, not only uploading, but also settings, even switching accounts.

**Comment by hlf20010508** [comment] 2024-06-12 14:26
Oh I remember if I disable the progress status, the transfer rate can be faster.
So I think if I lower the message updating rate, It should have a better performance.
For now the status is updated once a part is transferred.

**Comment by kaiser62** [comment] 2024-06-12 15:16
Yes you can try that. looking forward to that update.

**Comment by hlf20010508** [comment] 2024-06-16 07:17
I've set the progress status updating interval to 5 seconds.
But the improvement is not considerable.
I've done some research, and found that the problem is on OneDrive.
Although It support multi-part upload which should support multi-thread, but actually the parts can only be uploaded  in sequential order which means it is actually equal to single-thread. That's why I can't do much for it.

As to `.t2o` files, I've simply implemented it. You can have a try.

The dev image has been updated.

**Comment by hlf20010508** [comment] 2024-06-24 11:13
New version published.

**Closed by hlf20010508** 2024-06-24 11:13 UTC
